### ISSUE TITLE
Deep copy breaks on instances of EventEmitter in node versions 6.0.0 and onward

### ISSUE THREAD

**Issue by gtelljohann** [mrluc/owl-deepcopy#4]
In node 6.0.0, the EventEmitter instance's `_events` property is an object that is not an instance of the object prototype (so you can register an event for `__proto__` without things breaking...).  When deep copy tries to copy this object, it calls instanceof on something without a hasOwnProperty, which throws an error.

This is a problem because for some reason Mongoose schemas are instances of the EventEmitter class, so deep copying one throws an error.

**Comment by nodesocket** [comment]
Darn, still getting an error. Is this related?

```
/var/www/app/node_modules/owl-deepcopy/deep_copy.js:228
    if ( source instanceof source.constructor ) {
                                 ^

TypeError: Expecting a function in instanceof check, but got undefined
```
